const menu = [
  {
    id: 1,
    title: "potato tacos (G,M)",
    category: "starter",
    price: 139,
    img: "./images/potatotaco.jpg",
    desc: `Tortilla, coriander, peas, potato, pickle , Onion `,
  },
  {
    id: 10,
    title: "butter chicken",
    category: "Dinner",
    price: 249,
    img: "./images/butterchicken.jpg",
    desc: `Clay oven chicken tikka, creamy toamto sauce, mozrella and cashew gravy`,
  },
  {
    id: 11,
    title: "chicken briyani",
    category: "Dinner",
    price: 249,
    img: "./images/chickenbriyani.jpg",
    desc: `Aromatic rice cooked with chicken and indian spices`,
  },
  {
    id: 2,
    title: "momo (G,N)",
    category: "starter",
    price: 149,
    img: "./images/momo.jpg",
    desc: `Soft tender chicken,coriander, chilly, garlic, tomato chutney `,
  },
  {
    id: 3,
    title: "cripsy okra (G)",
    category: "starter",
    price: 129,
    img: "./images/crispyokra.jpg",
    desc: `Fried okra with onion, tomato, coriander, garlic and ginger`,
  },
  {
    id: 4,
    title: "sea food cracker(G)",
    category: "starter",
    price: 149,
    img: "./images/seafoodcracker.jpg",
    desc: `Mix seafood, lemon and five spices `,
  },
  {
    id: 5,
    title: "calamari pakora (G,M)",
    category: "starter",
    price: 159,
    img: "./images/kalamaripakora.jpg",
    desc: `Squid fritters, tomato, chickpeas flour `,
  },
  {
    id: 6,
    title: "1947 special salad",
    category: "starter",
    price: 109,
    img: "./images/1947salad.jpg",
    desc: `Lettuce with cucumber, tomato, onion, coriander, apple and chilly with special sauce`,
  },
  {
    id: 7,
    title: "devine tandoori chicken (M)",
    category: "starter",
    price: 199,
    img: "./images/divinetandorichicken.jpg",
    desc: `Chicken, lemon , koriander, yoghurt and spice`,
  },

  {
    id: 8,
    title: "chicken tikka (M)",
    category: "starter",
    price: 209,
    img: "./images/chickentika.jpg",
    desc: `chicken marinated in tandoori masala and grilled in clay oven`,
  },

  {
    id: 9,
    title: "beef halcyon (M)",
    category: "starter",
    price: 279,
    img: "./images/beefhalacans.jpg",
    desc: `Beef, cheese, jalapeno, tomato, cracker and chilli`,
  },

  {
    id: 12,
    title: "chicken tikka masala",
    category: "Dinner",
    price: 239,
    img: "./images/tikamasala.jpg",
    desc: `soft tender chicken,coriander, chilly, garlic, tomato chutney`,
  },
  {
    id: 13,
    title: "lamb shank rogan josh",
    category: "Dinner",
    price: 279,
    img: "./images/lambsahankroganjosh.jpg",
    desc: `Indian spiced slow cooked lamb shank`,
  },
  {
    id: 14,
    title: "palak paneer",
    category: "Dinner",
    price: 229,
    img: "./images/palakpaner.jpg",
    desc: `Indian mild flavour cheese cooked in fresh puree of spinach`,
  },
  {
    id: 15,
    title: "sea food moile",
    category: "Dinner",
    price: 269,
    img: "./images/seafoodmoili.jpg",
    desc: `Coconut flavour seafood gravy, chef special dish, you must try`,
  },
  {
    id: 16,
    title: " 1947 gandhi special COD",
    category: "Dinner",
    price: 299,
    img: "./images/1947specaialcod.jpg",
    desc: `Cod with chunky semi dry egg plant`,
  },
  {
    id: 17,
    title: " keema mattar",
    category: "Dinner",
    price: 299,
    img: "./images/keemamatar.jpg",
    desc: `Minced lamb  and fresh green peas in dry curry potato sauce`,
  },
  {
    id: 18,
    title: " gajarhalwa with pistachiice",
    category: "Dessert",
    price: 149,
    img: "./images/gajurhalwawithpistachiice.jpg",
    desc: `Red carrot minced and mixed with sweets, served with pistachiice ice`,
  },
  {
    id: 19,
    title: " rabadi with strawberry sorbet",
    category: "Dessert",
    price: 149,
    img: "./images/rabadiwithstrawberrysorbet.jpg",
    desc: `Milk made rabadi, served with strawberry sorbet`,
  },
];
export default menu;
